name: editorconfig-checker

on:
  pull_request:
  push:

jobs:
  build:
    name: editorconfig-checker
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
        with:
          persist-credentials: false
      - uses: editorconfig-checker/action-editorconfig-checker@1a41284d59c6fe7f1b21ddc4a2b36400a33dc1b4 # tag v2. is really out of date
      - run: editorconfig-checker
